FROM python:3.10-slim as builder

WORKDIR /build
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

FROM python:3.10-slim

WORKDIR /app
COPY --from=builder /usr/local/lib/python3.10/site-packages /usr/local/lib/python3.10/site-packages
COPY . .

ENV PYTHONPATH=/app

EXPOSE 8000 8001
ENTRYPOINT ["python3", "main.py"]
CMD ["--mode", "server"]
